### ISSUE TITLE
Postulacion de Miembros

### ISSUE THREAD

**Issue by aasanchez** [QRDA-VE/Website#1]
Las personas que deseen ser miembros del proyecto, favor comentar aqui

**Comment by zamuro** [comment]
¿Eso incluye a los "Fundadores"? Entiéndase, quienes asistimos a la primera
convocatoria.

El 9 de noviembre de 2015, 10:32, Alexis Sánchez notifications@github.com
escribió:

> Las personas que deseen ser miembros del proyecto, favor comentar aqui
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/QRDA-VE/Website/issues/1.

## 

MSc. Ing. Manuel Lucena Pérez
Cisco Certified Network Professional®
3Com WAN-LAN Specialist®
GNU/Linux User #409072
Debian User #261
Venezolana de Tecnologías, S.A. - Chief Technical Officer
m: +58 412 5156029
skype: mlucenap

**Comment by aasanchez** [comment]
Bueno la idea es que los que estaban en el otro repo se anoten, y de una vez esto quede para el futuro :D

**Comment by carloselhalabi** [comment]
:)
