### ISSUE TITLE
Nos vendría bien un logo

### ISSUE THREAD

**Issue by carloselhalabi** [QRDA-VE/Website#2]
Sería genial que los diseñadores o cualquiera interesado nos echasen la mano con darnos una imagen de representación y así mejorar el aspecto de la web. :muscle:

**Comment by zamuro** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hola

Ya Del Bosque hizo toda la identidad gráfica.

Está en un repo del equipo.

El 14/11/15 a las 22:03, Carlos El Halabi escribió:

> Sería genial que los diseñadores o cualquiera interesado nos
> echasen la mano con darnos una imagen de representación y así
> mejorar el aspecto de la web. :muscle:
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/QRDA-VE/Website/issues/2.

---

MSc. Ing. Manuel Lucena Pérez
Cisco Certified Network Professional®
3Com WAN-LAN Specialist®
GNU/Linux User #409072
Debian User #261
Venezolana de Tecnologías, S.A. - Chief Technical Officer
m: +58 412 5156029
skype: mlucenap
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJWSG1OAAoJELoVRjyX+zSbnnoIAMXftGSzk+1KYXxmFVEuYEAa
vgT7eAxr73NMTHgV18VtT8pyMQgRdJNRoLceHmn2x6eqW+5pSwOZ0tOfwrW/i1FO
FzOVv0wh7vkaev910H0ViuuPudD2f3uDg9uFcH9WXtyOwQqInGKKIc3HDq58Z9Iz
AzHdNFWr13YTzWH5B7Z7Ph0lIFfAhn+NAoktoxwVWiPsXPa/zqYYYLHVVj36VmEN
FkoVCgbw5SQYz6pspROcLL7YR8RbdLc+HoId/tLzWk6jbR05FOPkv/FUTli8KtAe
Ogd5D+JE2kpdScgoKJkjUSbDGMJLZJSA+o6SVsTmD6CRkiIvELsWAkeA07EtwZg=
=jMlP
-----END PGP SIGNATURE-----

**Comment by carloselhalabi** [comment]
Buscando de manera burda no pude encontrar el repo, si puedes compartir el enlace o el contenido estaría genial. 

Saludos!

**Comment by zamuro** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hola.

Déjame hablar con los muchachos. Tengo entendido que chuda había
pedido el retina display de todo eso.

El 15/11/15 a las 13:29, Carlos El Halabi escribió:

> Buscando de manera burda no pude encontrar el repo, si puedes
> compartir el enlace o el contenido estaría genial.
> 
> Saludos!
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/QRDA-VE/Website/issues/2#issuecomment-156839914.
> 
> ---
> 
> MSc. Ing. Manuel Lucena Pérez
> Cisco Certified Network Professional®
> 3Com WAN-LAN Specialist®
> GNU/Linux User #409072
> Debian User #261
> Venezolana de Tecnologías, S.A. - Chief Technical Officer
> m: +58 412 5156029
> skype: mlucenap
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v1

iQEcBAEBAgAGBQJWSMoLAAoJELoVRjyX+zSbn4QIAMa4Ziyp5tZBXDqCtZCzXQXI
KydKaXgD7ecME8F+oQzD0lpQl5H4p9OcDw1E6i3Ql3g1X4S4iGQ1rDNKwgAyuQim
enEb1DEJeOKd7XKiyjwEecjQpDMp9mF6WPyFBLS9DLnBcm8GfU2UZ7GYoOQMyMiI
RbSzR8rxZnNR4XJp84CzOTvKGZBRIztZHIjFQc3DtNH94KlzCNUfwKoPLg7DeA6o
ArSZiiVaACVVtUzdc5g63z4YYUFV5Z1KlkoRyy2uZWivIainwGLnyoXMx6XGBJp2
gVPwL14MWk2y+qQvU8AYNrjOIV4S2vvJVBWdjR6E+Nan1iKLn1vQRkU3X4/yWO4=
=U8TF
-----END PGP SIGNATURE-----

**Comment by carloselhalabi** [comment]
¿Algún avance con ésto? ^^
